services:
  mongo:
    image: mongo:8.0.10-rc0
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - oacis_network
    ports:
      - "27017:27017"

  redis:
    image: redis:8.0.1
    networks:
      - oacis_network

  web:
    build: ./docker/web
    command: bundle exec rails s -b 0.0.0.0
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    networks:
      - oacis_network
    depends_on:
      - mongo
      - redis

  job_submitter:
    build: ./docker/web
    working_dir: /oacis/lib/tasks
    command: bundle exec ruby -r '/oacis/config/environment.rb' ./boot_job_submitter_worker.rb start
    networks:
      - oacis_network
    depends_on:
      - web

  job_observer:
    build: ./docker/web
    working_dir: /oacis/lib/tasks
    command: bundle exec ruby -r '/oacis/config/environment.rb' ./boot_job_observer_worker.rb start
    networks:
      - oacis_network 
    depends_on:
      - web

  service_worker:
    build: ./docker/web
    working_dir: /oacis/lib/tasks
    command: bundle exec ruby -r '/oacis/config/environment.rb' ./boot_service_worker.rb start
    networks:
      - oacis_network
    depends_on:
      - web

volumes:
  mongodb_data:

networks:
  oacis_network:
    driver: bridge