services:
  mongo:
    image: mongo:8.0.10-rc0
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - oacis_network

  redis:
    image: redis:8.0.1
    networks:
      - oacis_network

  web:
    build: ./docker/web
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    networks:
      - oacis_network
    depends_on:
      - mongo
      - redis

  sidekiq:
    build: ./docker/web
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      - RAILS_ENV=development
    networks:
      - oacis_network
    depends_on:
      - web

volumes:
  mongodb_data:

networks:
  oacis_network:
    driver: bridge