services:
  mongo:
    image: mongo:8.0.10-rc0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - oacis_network
  redis:
    image: redis:8.0.1
    networks:
      - oacis_network

volumes:
  mongodb_data:

networks:
  oacis_network:
    driver: bridge