services:
  mongo:
    image: mongo:8.0.10-rc0
    restart: always
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:8.0.1

  web:
    build: ./docker/web
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  sidekiq:
    build: ./docker/web
    command: bundle exec sidekiq
    environment:
      - RAILS_ENV=development
    depends_on:
      - web

volumes:
  mongodb_data: