services:
  mongo:
    image: mongo:8.0.10-rc0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports: # For debug. Not necessary for production
      - "27017:27017"

  redis:
    image: redis:8.0.1
    ports: # For debug. Not necessary for production
      - "6379:6379"

  web:
    build: ./docker/web
    volumes:
      - result_development:/oacis/public/Result_development
      - type: bind
        source: ./.ssh/config
        target: /root/.ssh/config
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
    environment:
      - RAILS_ENV=development
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
      - TZ=${TZ:-utc} # Dockerホストの TZ 環境変数を参照. ない場合は utc
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  sidekiq:
    build: ./docker/web
    command: bundle exec sidekiq
    volumes:
      - worker_logs:/oacis/log
      - result_development:/oacis/public/Result_development
      - type: bind
        source: ./.ssh/config
        target: /root/.ssh/config
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
    environment:
      - RAILS_ENV=development
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
      - TZ=${TZ:-utc} # Dockerホストの TZ 環境変数を参照. ない場合は utc
    depends_on:
      - web

volumes:
  mongo_data:
  worker_logs:
  result_development: