services:
  mongo:
    image: mongo:8.0.10-rc0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:8.0.1

  web:
    build: ./docker/web
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  sidekiq:
    build: ./docker/web
    command: bundle exec sidekiq
    environment:
      - RAILS_ENV=development
    volumes:
      - ./docker/web/app/workers/parameter_sets_creator.rb:/oacis/app/workers/parameter_sets_creator.rb
      - worker_logs:/oacis/log
    depends_on:
      - web

volumes:
  mongo_data:
  worker_logs: