services:
  mongo:
    image: mongo:8.0.10-rc0
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - oacis_network
    ports:
      - "27017:27017"
  redis:
    image: redis:8.0.1
    networks:
      - oacis_network
  rails:
    build: ./docker/rails
    ports:
      - "3000:3000"
    networks:
      - oacis_network

volumes:
  mongodb_data:

networks:
  oacis_network:
    driver: bridge